baseURL = 'https://juliogmz89.github.io/'
languageCode = 'en-us'
title = 'Julio César Gómez González '
theme = 'blowfish'

[params]
  colorScheme = 'noir'
  defaultTheme = 'dark'
  logo = "images/gosh-rat/gosh-rat-face-background-128.png"
  dateFormat = "2006"
  
  [params.header]
    layout = 'fixed'

  [params.footer]
    showScrollToTop = true

  [params.homepage]
    layout = 'background'
    showRecent = true
    cardView = true
    cardViewScreenWidth = false

  [params.article]
    showTaxonomies = true
    showHero = true
    heroStyle = "background"

  [params.list]
    showCards = true
    cardView = true

  [params.author]
    name = "Julio César Gómez González"
    image = "images/gosh-rat/gosh-rat-background.png"
    headline = "Software Engineer"
    links = [
      { github = "https://github.com/JulioGmz89" },
      { linkedin = "https://www.linkedin.com/in/juliogmz89/" },
    ]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 30
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 40
