baseURL = 'https://juliogmz89.github.io/'
theme = 'blowfish'
defaultContentLanguage = 'en'
timeout = "5m"

[languages]
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 1
    title = 'Julio César Gómez González'
    [languages.en.params]
      displayName = 'English'
      dateFormat = '2006'

  [languages.es]
    languageCode = 'es'
    languageName = 'Español'
    weight = 2
    title = 'Julio César Gómez González'
    [languages.es.params]
      displayName = 'Español'
      dateFormat = '2006'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  colorScheme = 'noir'
  defaultTheme = 'dark'
  logo = "images/gosh-rat/gosh-rat-face-background-128.png"
  dateFormat = "2006"
  enableSearch = true
  defaultBackgroundImage = "images/background/homepage-background.jpg"
  disableImageOptimizationMD = true
  mainSections = ["projects"]
  
  [params.header]
    layout = 'fixed'

  [params.footer]
    showScrollToTop = true

  [params.homepage]
    layout = 'background'
    homepageImage = "images/background/homepage-background.jpg"
    showRecent = true
    cardView = true
    cardViewScreenWidth = false

  [params.article]
    showTaxonomies = true
    showHero = false
    
  [params.list]
    showCards = true
    cardView = true

  [params.author]
    name = "Julio César Gómez González"
    image = "images/gosh-rat/gosh-rat-background.png"
    headline = "Software Engineer | Game Developer"
    links = [
      { github = "https://github.com/JulioGmz89" },
      { linkedin = "https://www.linkedin.com/in/juliogmz89/" },
    ]

# English Menu
[[languages.en.menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10
[[languages.en.menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 20
[[languages.en.menu.main]]
  identifier = "devlog"
  name = "Devlog"
  url = "/devlog/"
  weight = 25
# [[languages.en.menu.main]]
#   identifier = "posts"
#   name = "Blog"
#   url = "/posts/"
#   weight = 30
[[languages.en.menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "/resume/"
  weight = 40

# Spanish Menu
[[languages.es.menu.main]]
  identifier = "about"
  name = "Acerca de"
  url = "/es/about/"
  weight = 10
[[languages.es.menu.main]]
  identifier = "projects"
  name = "Proyectos"
  url = "/es/projects/"
  weight = 20
[[languages.es.menu.main]]
  identifier = "devlog"
  name = "Devlog"
  url = "/es/devlog/"
  weight = 25
# [[languages.es.menu.main]]
#   identifier = "posts"
#   name = "Blog"
#   url = "/es/posts/"
#   weight = 30
[[languages.es.menu.main]]
  identifier = "resume"
  name = "Currículum"
  url = "/es/resume/"
  weight = 40
